#!/bin/bash
set -e

DISK=/dev/nvme0n1
SSD_HOME=/dev/sda  # 确认直接使用整块裸盘

echo ">>> 分区磁盘 (${DISK})"
parted -s $DISK mklabel gpt
parted -s $DISK mkpart primary fat32 1MiB 1025MiB          # p1 EFI 1G
parted -s $DISK mkpart primary linux-swap 1025MiB 9217MiB  # p2 SWAP 8G
parted -s $DISK mkpart primary ext4 9217MiB 100%           # p3 根分区

echo ">>> 格式化 NVMe 分区"
mkfs.fat -F32 ${DISK}p1 -n EFI
mkswap ${DISK}p2 -L SWAP
mkfs.ext4 -F ${DISK}p3 -L ROOT

echo ">>> 挂载分区"
mount ${DISK}p3 /mnt
mkdir -p /mnt/boot/efi
mkdir -p /mnt/home

mount ${DISK}p1 /mnt/boot/efi
# 挂载整块 SSD 到 /home
mount ${SSD_HOME} /mnt/home
swapon ${DISK}p2

echo ">>> 安装基础系统"
# 加上 vim 和 sudo
pacstrap /mnt base base-devel linux linux-firmware intel-ucode gvim networkmanager grub efibootmgr

echo ">>> 生成 fstab"
genfstab -U /mnt >> /mnt/etc/fstab

echo ">>> 进入 chroot 环境并配置系统"
arch-chroot /mnt /bin/bash <<EOF
set -e

# 时区与硬件时钟（使用 UTC 避免系统日志和时间同步冲突）
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
hwclock --systohc

# 设置 locale
sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
sed -i 's/^#zh_CN.UTF-8 UTF-8/zh_CN.UTF-8 UTF-8/' /etc/locale.gen
locale-gen

echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "archlinux" > /etc/hostname

# 启用网络服务
systemctl enable NetworkManager

echo ">>> 安装与配置 systemd-boot"
# 1. 初始化 systemd-boot 文件到 /boot
bootctl install

# 2. 获取根分区 (nvme0n1p3) 的 UUID
ROOT_UUID=\$(blkid -s UUID -o value ${DISK}p3)

# 3. 创建全局加载配置 loader.conf
cat <<CONF > /boot/loader/loader.conf
default  arch.conf
timeout  3
console-mode max
editor   no
CONF

# 4. 创建 Arch Linux 的具体启动项配置 arch.conf
cat <<CONF > /boot/loader/entries/arch.conf
title   Arch Linux
linux   /vmlinuz-linux
initrd  /intel-ucode.img
initrd  /initramfs-linux.img
options root=UUID=\${ROOT_UUID} rw
# options root=/dev/nvme0n1p2 rw

# home目录存在后直接 -d 指定目录，如果home目录不存在用 -m 新建文件夹
echo ">>> 新建用户 monkey"
useradd -d /home/monkey -G wheel -s /bin/bash monkey

# useradd -m -G wheel -s /bin/bash monkey

EOF

echo ">>> 安装完成！正在卸载分区..."
umount -R /mnt
echo ">>> 安全卸载完成，可以放心重启系统了！"
